env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  camelcase: 'off'
  import/no-cycle: 'off'
  import/no-extraneous-dependencies: 'off'
  import/no-unresolved: 'off'
  import/prefer-default-export: 'off'
  import/extensions: 'off'
  jsx-a11y/anchor-is-valid: 'off'
  jsx-a11y/click-events-have-key-events: 'off'
  jsx-a11y/href-no-hash: 'off'
  jsx-a11y/label-has-for: 'off'
  jsx-a11y/no-static-element-interactions: 'off'
  react/destructuring-assignment: 'off'
  react/jsx-filename-extension: 'off'
  react/jsx-indent: 'off'
  react/jsx-one-expression-per-line: 'off'
  react/jsx-uses-react: 1
  react/jsx-uses-vars: 1
  react/jsx-wrap-multilines: 'off'
  react/no-array-index-key: 'off'
  react/no-unescaped-entities: 'off'
  react/prop-types: 'off'
  react/sort-comp: 'off'
  array-callback-return: 'off'
